const PDFDocument = require('pdfkit');
const { formatCurrency, formatDateHindi, getEntryTypeHindi, getStatusHindi } = require('./helpers');

class KhataPDFGenerator {
  constructor(entries, title = 'खाता रिपोर्ट') {
    this.entries = entries;
    this.title = title;
    this.doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      info: {
        Title: title,
        Author: 'Gaon Khata Manager',
        Subject: 'Land Khata Report',
        Creator: 'Gaon Khata Manager',
        Producer: 'Gaon Khata Manager'
      }
    });
  }

  generate() {
    this.addHeader();
    this.addSummary();
    this.addTable();
    this.addFooter();
    return this.doc;
  }

  addHeader() {
    // Header background
    this.doc.rect(0, 0, this.doc.page.width, 120).fill('#1a472a');
    
    // Title
    this.doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor('white')
      .text('Gaon Khata Manager', 50, 30, { align: 'center' });
    
    this.doc
      .fontSize(16)
      .font('Helvetica')
      .fillColor('#d4a373')
      .text(this.title, { align: 'center' });
    
    this.doc.moveDown(2);
    this.doc.fillColor('black');
  }

  addSummary() {
    const totalAmount = this.entries.reduce((sum, e) => sum + e.financials.totalAmount, 0);
    const totalPaid = this.entries.reduce((sum, e) => sum + e.financials.paidAmount, 0);
    const totalPending = this.entries.reduce((sum, e) => sum + e.financials.remainingAmount, 0);
    
    this.doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('सारांश (Summary)', { underline: true });
    
    this.doc.moveDown(0.5);
    
    this.doc.font('Helvetica');
    const summaryData = [
      ['कुल प्रविष्टियाँ', this.entries.length.toString()],
      ['कुल राशि', formatCurrency(totalAmount)],
      ['कुल भुगतान', formatCurrency(totalPaid)],
      ['कुल बकाया', formatCurrency(totalPending)]
    ];
    
    summaryData.forEach(([label, value]) => {
      this.doc
        .fontSize(11)
        .text(`${label}: ${value}`, { continued: false });
    });
    
    this.doc.moveDown(1.5);
  }

  addTable() {
    const tableTop = this.doc.y + 10;
    const tableHeaders = ['दिनांक', 'व्यक्ति', 'प्रकार', 'कुल राशि', 'भुगतान', 'बकाया', 'स्थिति'];
    const columnWidths = [70, 100, 60, 80, 80, 80, 60];
    
    // Table header background
    this.doc.rect(50, tableTop, this.doc.page.width - 100, 25).fill('#1a472a');
    
    // Table header text
    this.doc.fillColor('white').font('Helvetica-Bold').fontSize(9);
    
    let xPosition = 55;
    tableHeaders.forEach((header, i) => {
      this.doc.text(header, xPosition, tableTop + 7, {
        width: columnWidths[i],
        align: 'center'
      });
      xPosition += columnWidths[i];
    });
    
    // Table rows
    this.doc.fillColor('black').font('Helvetica').fontSize(8);
    let yPosition = tableTop + 30;
    
    this.entries.forEach((entry, index) => {
      // Alternate row background
      if (index % 2 === 0) {
        this.doc.rect(50, yPosition - 3, this.doc.page.width - 100, 20).fill('#f0f4f1');
        this.doc.fillColor('black');
      }
      
      const rowData = [
        formatDateHindi(entry.date),
        entry.person?.name || 'N/A',
        getEntryTypeHindi(entry.entryType),
        formatCurrency(entry.financials.totalAmount),
        formatCurrency(entry.financials.paidAmount),
        formatCurrency(entry.financials.remainingAmount),
        getStatusHindi(entry.status)
      ];
      
      let xPos = 55;
      rowData.forEach((data, i) => {
        this.doc.text(data, xPos, yPosition, {
          width: columnWidths[i],
          align: i > 2 ? 'right' : 'left'
        });
        xPos += columnWidths[i];
      });
      
      yPosition += 20;
      
      // Add new page if needed
      if (yPosition > this.doc.page.height - 80) {
        this.doc.addPage();
        yPosition = 50;
      }
    });
  }

  addFooter() {
    const pages = this.doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      this.doc.switchToPage(i);
      
      this.doc
        .fontSize(8)
        .fillColor('gray')
        .text(
          `Generated by Gaon Khata Manager | Page ${i + 1} of ${pages.count}`,
          50,
          this.doc.page.height - 50,
          { align: 'center' }
        );
    }
  }
}

module.exports = KhataPDFGenerator;
